(function(){"use strict";
const SESSION_URL="../api/auth/session.php",LOGOUT_URL="../api/auth/logout.php",NAV_URL="../api/aluno/navegacao.php",LOGIN_PAGE="login.html";
const ROLE_PAGES={admin:"dashboard.html",professor:"professor.html",responsavel:"responsavel.html",secretaria:"dashboard.html"};let cached=null;
async function readJson(r){try{return await r.json()}catch{return null}}
function clear(){["primewayLogado","primewayUsuario","primewayPerfil"].forEach(k=>sessionStorage.removeItem(k))}
async function getSession(force=false){if(cached&&!force)return cached;const r=await fetch(SESSION_URL,{credentials:"same-origin",cache:"no-store",headers:{Accept:"application/json"}}),d=await readJson(r);if(!r.ok||!d?.authenticated||!d.usuario){cached=null;return null}cached=d;return d}
async function ensureStudent(){try{const s=await getSession(true);if(!s){clear();location.replace(LOGIN_PAGE);return null}const role=String(s.usuario.perfil||"");if(role!=="aluno"){location.replace(ROLE_PAGES[role]||LOGIN_PAGE);return null}return s}catch(e){console.error("Erro ao validar sessão do aluno:",e);clear();location.replace(LOGIN_PAGE);return null}}
async function request(url,opt={}){const c={method:opt.method||"GET",credentials:"same-origin",cache:opt.cache||"no-store",headers:{Accept:"application/json",...(opt.headers||{})}};if(opt.body!==undefined)c.body=opt.body;const m=String(c.method).toUpperCase();if(!["GET","HEAD"].includes(m)){const s=await getSession();c.headers["X-CSRF-Token"]=s?.csrfToken||""}const r=await fetch(url,c),d=await readJson(r);if(r.status===401){clear();cached=null;location.replace(LOGIN_PAGE)}return{response:r,data:d}}
async function requestJson(url,payload,method="POST"){return request(url,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)})}
async function logout(){const b=document.querySelector("#logoutButton");if(b)b.disabled=true;try{const s=await getSession(true),r=await fetch(LOGOUT_URL,{method:"POST",credentials:"same-origin",headers:{Accept:"application/json","X-CSRF-Token":s?.csrfToken||""}}),d=await readJson(r);if(!r.ok||!d?.success)throw new Error(d?.message||"Não foi possível encerrar a sessão.");clear();cached=null;location.replace(LOGIN_PAGE)}catch(e){console.error(e);window.PrimeWayFeedback?.error(e?.message||"Não foi possível encerrar a sessão.");if(b)b.disabled=false}}
function bindLogout(){const b=document.querySelector("#logoutButton");if(!b||b.dataset.primewayBound==="1")return;b.dataset.primewayBound="1";b.addEventListener("click",logout)}
function formatDate(value,withTime=false){if(!value)return"—";const n=String(value).includes("T")?String(value):String(value).replace(" ","T"),p=new Date(n.length===10?`${n}T12:00:00`:n);if(Number.isNaN(p.getTime()))return String(value);return new Intl.DateTimeFormat("pt-BR",withTime?{dateStyle:"short",timeStyle:"short"}:{dateStyle:"short"}).format(p)}
function setBadge(name,value){const e=document.querySelector(`[data-nav-badge="${name}"]`);if(!e)return;const n=Number(value||0);if(!Number.isFinite(n)||n<=0){e.hidden=true;e.textContent="0";return}e.hidden=false;e.textContent=n>99?"99+":String(n)}
async function refreshNavigationBadges(){try{const r=await fetch(NAV_URL,{credentials:"same-origin",cache:"no-store",headers:{Accept:"application/json"}}),d=await readJson(r);if(!r.ok||!d?.success)return;setBadge("notifications",d.unreadNotifications);setBadge("chat",d.unreadMessages)}catch(e){console.debug("Contadores indisponíveis:",e)}}
window.PrimeWayAluno=Object.freeze({readJson,getSession,ensureStudent,request,requestJson,logout,bindLogout,formatDate,refreshNavigationBadges});
document.addEventListener("DOMContentLoaded",()=>refreshNavigationBadges());
})();